# Generated by Django 4.0.2 on 2022-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=200)),
                ('L_Name', models.CharField(max_length=200)),
                ('E_Mail', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Create_Password', models.CharField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=100)),
                ('Art_Type', models.CharField(max_length=100)),
            ],
        ),
    ]
